CREATE TABLE nfl_game_player_stats_2024 (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id TEXT NOT NULL,
    season INT NOT NULL,
    player_id UUID NOT NULL REFERENCES nfl_players_2025(id) ON DELETE CASCADE,
    week INT NOT NULL,
    passing_yards INT DEFAULT 0,
    passing_touchdowns INT DEFAULT 0,
    passing_attempts INT DEFAULT 0,
    passing_completions INT DEFAULT 0,
    passing_incomplete_passes INT DEFAULT 0,
    sacks INT DEFAULT 0,
    interceptions INT DEFAULT 0,
    rushing_yards INT DEFAULT 0,
    rushing_attempts INT DEFAULT 0,
    rushing_touchdowns INT DEFAULT 0,
    fumbles INT DEFAULT 0,
    rush_attempts_inside_10 INT DEFAULT 0,
    rush_attempts_inside_5 INT DEFAULT 0,
    rush_attempts_inside_2 INT DEFAULT 0,
    rushes_on_1rd_down INT DEFAULT 0,
    rushes_on_2rd_down INT DEFAULT 0,
    rushes_on_3rd_down INT DEFAULT 0,
    rushes_10_plus INT DEFAULT 0,
    rushes_20_plus INT DEFAULT 0,
    receptions INT DEFAULT 0,
    receiving_yards INT DEFAULT 0,
    receiving_touchdowns INT DEFAULT 0,
    yards_after_catch INT DEFAULT 0,
    targets INT DEFAULT 0,
    targets_on_1rd_down INT DEFAULT 0,
    targets_on_2rd_down INT DEFAULT 0,
    targets_on_3rd_down INT DEFAULT 0,
    targets_10_plus INT DEFAULT 0,
    targets_20_plus INT DEFAULT 0,
    redzone_targets INT DEFAULT 0
);
