-- Rename nfl_players_2025 to nfl_players and add year column
ALTER TABLE nfl_players_2025 RENAME TO nfl_players;

-- Add year column with default value of 2025
ALTER TABLE nfl_players ADD COLUMN year INTEGER DEFAULT 2025;

-- Create fantasy_team_weekly_stats table
CREATE TABLE fantasy_team_weekly_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    league_id UUID NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    week INTEGER NOT NULL,
    year INTEGER NOT NULL,
    win BOOLEAN NOT NULL,
    points_for DECIMAL(10,2) NOT NULL,
    points_against DECIMAL(10,2) NOT NULL,
    max_possible_points DECIMAL(10,2) NOT NULL,
    opponent_team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_id, team_id, week, year)
);

-- Create fantasy_team_season_stats table
CREATE TABLE fantasy_team_season_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    league_id UUID NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    points_for DECIMAL(10,2) NOT NULL DEFAULT 0,
    points_against DECIMAL(10,2) NOT NULL DEFAULT 0,
    max_possible_points DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_id, team_id, year)
);

-- Create fantasy_player_weekly_stats table
CREATE TABLE fantasy_player_weekly_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    player_id UUID NOT NULL REFERENCES nfl_players(id) ON DELETE CASCADE,
    game_id UUID NOT NULL REFERENCES nfl_schedule(id) ON DELETE CASCADE,
    week INTEGER NOT NULL,
    year INTEGER NOT NULL,
    team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    projected_fantasy_points DECIMAL(10,2) NOT NULL DEFAULT 0,
    actual_fantasy_points DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, game_id, week, year)
);

-- Create fantasy_player_yearly_stats table
CREATE TABLE fantasy_player_season_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    player_id UUID NOT NULL REFERENCES nfl_players(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    games_played INTEGER NOT NULL DEFAULT 0,
    avg_projected_fantasy_points DECIMAL(10,2) NOT NULL DEFAULT 0,
    std_dev_projected_fantasy_points DECIMAL(10,2) NOT NULL DEFAULT 0,
    avg_actual_fantasy_points DECIMAL(10,2) NOT NULL DEFAULT 0,
    std_dev_actual_fantasy_points DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, year)
);

-- Create nfl_player_weekly_stats table
CREATE TABLE nfl_player_weekly_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    player_id UUID NOT NULL REFERENCES nfl_players(id) ON DELETE CASCADE,
    game_id UUID NOT NULL REFERENCES nfl_schedule(id) ON DELETE CASCADE,
    week INTEGER NOT NULL,
    year INTEGER NOT NULL,
    injured BOOLEAN NOT NULL DEFAULT FALSE,
    got_injured BOOLEAN NOT NULL DEFAULT FALSE,
    passing_touchdowns INTEGER NOT NULL DEFAULT 0,
    passing_attempts INTEGER NOT NULL DEFAULT 0,
    passing_completions INTEGER NOT NULL DEFAULT 0,
    passing_incompletions INTEGER NOT NULL DEFAULT 0,
    passing_interceptions INTEGER NOT NULL DEFAULT 0,
    passing_yards INTEGER NOT NULL DEFAULT 0,
    rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    rushing_attempts INTEGER NOT NULL DEFAULT 0,
    rushing_yards INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_20 INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_10 INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_5 INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_2 INTEGER NOT NULL DEFAULT 0,
    rushes_on_1st_down INTEGER NOT NULL DEFAULT 0,
    rushes_on_2nd_down INTEGER NOT NULL DEFAULT 0,
    rushes_on_3rd_down INTEGER NOT NULL DEFAULT 0,
    rushes_10_plus INTEGER NOT NULL DEFAULT 0,
    rushes_20_plus INTEGER NOT NULL DEFAULT 0,
    receptions INTEGER NOT NULL DEFAULT 0,
    receiving_yards INTEGER NOT NULL DEFAULT 0,
    receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    receiving_yards_after_catch INTEGER NOT NULL DEFAULT 0,
    targets INTEGER NOT NULL DEFAULT 0,
    targets_on_1st_down INTEGER NOT NULL DEFAULT 0,
    targets_on_2nd_down INTEGER NOT NULL DEFAULT 0,
    targets_on_3rd_down INTEGER NOT NULL DEFAULT 0,
    targets_10_plus INTEGER NOT NULL DEFAULT 0,
    targets_20_plus INTEGER NOT NULL DEFAULT 0,
    targets_inside_20 INTEGER NOT NULL DEFAULT 0,
    targets_inside_10 INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, game_id, week, year)
);

-- Create nfl_player_season_stats table
CREATE TABLE nfl_player_season_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    player_id UUID NOT NULL REFERENCES nfl_players(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    games_played INTEGER NOT NULL DEFAULT 0,
    passing_touchdowns INTEGER NOT NULL DEFAULT 0,
    passing_attempts INTEGER NOT NULL DEFAULT 0,
    passing_completions INTEGER NOT NULL DEFAULT 0,
    passing_incompletions INTEGER NOT NULL DEFAULT 0,
    passing_interceptions INTEGER NOT NULL DEFAULT 0,
    passing_yards INTEGER NOT NULL DEFAULT 0,
    rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    rushing_attempts INTEGER NOT NULL DEFAULT 0,
    rushing_yards INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_20 INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_10 INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_5 INTEGER NOT NULL DEFAULT 0,
    rush_attempts_inside_2 INTEGER NOT NULL DEFAULT 0,
    rushes_on_1st_down INTEGER NOT NULL DEFAULT 0,
    rushes_on_2nd_down INTEGER NOT NULL DEFAULT 0,
    rushes_on_3rd_down INTEGER NOT NULL DEFAULT 0,
    rushes_10_plus INTEGER NOT NULL DEFAULT 0,
    rushes_20_plus INTEGER NOT NULL DEFAULT 0,
    receptions INTEGER NOT NULL DEFAULT 0,
    receiving_yards INTEGER NOT NULL DEFAULT 0,
    receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    receiving_yards_after_catch INTEGER NOT NULL DEFAULT 0,
    targets INTEGER NOT NULL DEFAULT 0,
    targets_on_1st_down INTEGER NOT NULL DEFAULT 0,
    targets_on_2nd_down INTEGER NOT NULL DEFAULT 0,
    targets_on_3rd_down INTEGER NOT NULL DEFAULT 0,
    targets_10_plus INTEGER NOT NULL DEFAULT 0,
    targets_20_plus INTEGER NOT NULL DEFAULT 0,
    targets_inside_20 INTEGER NOT NULL DEFAULT 0,
    targets_inside_10 INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, year)
);

-- Create nfl_team_weekly_stats table
CREATE TABLE nfl_team_weekly_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    team_id UUID NOT NULL REFERENCES nfl_teams(id) ON DELETE CASCADE,
    game_id UUID NOT NULL REFERENCES nfl_schedule(id) ON DELETE CASCADE,
    week INTEGER NOT NULL,
    year INTEGER NOT NULL,
    win BOOLEAN NOT NULL DEFAULT false,
    offense_total_plays INTEGER NOT NULL DEFAULT 0,
    defense_total_plays INTEGER NOT NULL DEFAULT 0,
    offense_redzone_plays INTEGER NOT NULL DEFAULT 0,
    defense_redzone_plays INTEGER NOT NULL DEFAULT 0,
    offense_redzone_trips INTEGER NOT NULL DEFAULT 0,
    offense_redzone_success_touchdown INTEGER NOT NULL DEFAULT 0,
    offense_redzone_success_field_goal INTEGER NOT NULL DEFAULT 0,
    defense_redzone_trips_allowed INTEGER NOT NULL DEFAULT 0,
    defense_redzone_touchdowns INTEGER NOT NULL DEFAULT 0,
    defense_redzone_field_goals INTEGER NOT NULL DEFAULT 0,
    defense_redzone_no_points INTEGER NOT NULL DEFAULT 0,
    offense_time_of_possession INTEGER NOT NULL DEFAULT 0,
    offense_pass_plays INTEGER NOT NULL DEFAULT 0,
    offense_run_plays INTEGER NOT NULL DEFAULT 0,
    offense_pass_completions INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_targets INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_receptions INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_receiving_yards INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_targets INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_receptions INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_receiving_yards INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_running_back_targets INTEGER NOT NULL DEFAULT 0,
    offense_running_back_receptions INTEGER NOT NULL DEFAULT 0,
    offense_running_back_receiving_yards INTEGER NOT NULL DEFAULT 0,
    offense_running_back_receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_running_back_rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_running_back_rushing_yards INTEGER NOT NULL DEFAULT 0,
    offense_quarterback_rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_quarterback_rushing_yards INTEGER NOT NULL DEFAULT 0,
    defense_wide_receiver_receptions_allowed INTEGER NOT NULL DEFAULT 0,
    defense_wide_receiver_receiving_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_wide_receiver_receiving_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_tight_end_receptions_allowed INTEGER NOT NULL DEFAULT 0,
    defense_tight_end_receiving_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_tight_end_receiving_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_receptions_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_receiving_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_receiving_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_rushing_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_rush_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_quarterback_rushing_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_quarterback_rushing_yards_allowed INTEGER NOT NULL DEFAULT 0,
    offense_points_scored INTEGER NOT NULL DEFAULT 0,
    defense_points_allowed INTEGER NOT NULL DEFAULT 0,
    offense_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_field_goals_made INTEGER NOT NULL DEFAULT 0,
    offense_field_goals_attempted INTEGER NOT NULL DEFAULT 0,
    defense_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_field_goals_allowed INTEGER NOT NULL DEFAULT 0,
    offense_extra_points INTEGER NOT NULL DEFAULT 0,
    offense_two_point_conversions INTEGER NOT NULL DEFAULT 0,
    offense_total_passing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_total_rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_passing_yards INTEGER NOT NULL DEFAULT 0,
    defense_passing_yards_allowed INTEGER NOT NULL DEFAULT 0,
    offense_rushing_yards INTEGER NOT NULL DEFAULT 0,
    defense_rushing_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_interceptions INTEGER NOT NULL DEFAULT 0,
    offense_interceptions_thrown INTEGER NOT NULL DEFAULT 0,
    offense_sacks_allowed INTEGER NOT NULL DEFAULT 0,
    defense_sacks INTEGER NOT NULL DEFAULT 0,
    offense_fumbles_lost INTEGER NOT NULL DEFAULT 0,
    defense_fumbles_recovered INTEGER NOT NULL DEFAULT 0,
    defense_fumble_touchdowns INTEGER NOT NULL DEFAULT 0,
    defense_interception_touchdowns INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(team_id, game_id, week, year)
);

create table nfl_team_season_stats (
    id uuid primary key default uuid_generate_v4(),
    team_id uuid references nfl_teams(id) on delete cascade,
    year INTEGER NOT NULL,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    offense_total_plays INTEGER NOT NULL DEFAULT 0,
    defense_total_plays INTEGER NOT NULL DEFAULT 0,
    offense_redzone_plays INTEGER NOT NULL DEFAULT 0,
    defense_redzone_plays INTEGER NOT NULL DEFAULT 0,
    offense_redzone_trips INTEGER NOT NULL DEFAULT 0,
    offense_redzone_success_touchdown INTEGER NOT NULL DEFAULT 0,
    offense_redzone_success_field_goal INTEGER NOT NULL DEFAULT 0,
    defense_redzone_trips_allowed INTEGER NOT NULL DEFAULT 0,
    defense_redzone_touchdowns INTEGER NOT NULL DEFAULT 0,
    defense_redzone_field_goals INTEGER NOT NULL DEFAULT 0,
    defense_redzone_no_points INTEGER NOT NULL DEFAULT 0,
    offense_time_of_possession INTEGER NOT NULL DEFAULT 0,
    offense_pass_plays INTEGER NOT NULL DEFAULT 0,
    offense_run_plays INTEGER NOT NULL DEFAULT 0,
    offense_pass_completions INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_targets INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_receptions INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_receiving_yards INTEGER NOT NULL DEFAULT 0,
    offense_wide_receiver_receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_targets INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_receptions INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_receiving_yards INTEGER NOT NULL DEFAULT 0,
    offense_tight_end_receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_running_back_targets INTEGER NOT NULL DEFAULT 0,
    offense_running_back_receptions INTEGER NOT NULL DEFAULT 0,
    offense_running_back_receiving_yards INTEGER NOT NULL DEFAULT 0,
    offense_running_back_receiving_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_running_back_rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_running_back_rushing_yards INTEGER NOT NULL DEFAULT 0,
    offense_quarterback_rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_quarterback_rushing_yards INTEGER NOT NULL DEFAULT 0,
    defense_wide_receiver_receptions_allowed INTEGER NOT NULL DEFAULT 0,
    defense_wide_receiver_receiving_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_wide_receiver_receiving_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_tight_end_receptions_allowed INTEGER NOT NULL DEFAULT 0,
    defense_tight_end_receiving_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_tight_end_receiving_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_receptions_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_receiving_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_receiving_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_rushing_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_running_back_rush_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_quarterback_rushing_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_quarterback_rushing_yards_allowed INTEGER NOT NULL DEFAULT 0,
    offense_points_scored INTEGER NOT NULL DEFAULT 0,
    defense_points_allowed INTEGER NOT NULL DEFAULT 0,
    offense_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_field_goals_made INTEGER NOT NULL DEFAULT 0,
    offense_field_goals_attempted INTEGER NOT NULL DEFAULT 0,
    defense_touchdowns_allowed INTEGER NOT NULL DEFAULT 0,
    defense_field_goals_allowed INTEGER NOT NULL DEFAULT 0,
    offense_extra_points INTEGER NOT NULL DEFAULT 0,
    offense_two_point_conversions INTEGER NOT NULL DEFAULT 0,
    offense_total_passing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_total_rushing_touchdowns INTEGER NOT NULL DEFAULT 0,
    offense_passing_yards INTEGER NOT NULL DEFAULT 0,
    defense_passing_yards_allowed INTEGER NOT NULL DEFAULT 0,
    offense_rushing_yards INTEGER NOT NULL DEFAULT 0,
    defense_rushing_yards_allowed INTEGER NOT NULL DEFAULT 0,
    defense_interceptions INTEGER NOT NULL DEFAULT 0,
    offense_interceptions_thrown INTEGER NOT NULL DEFAULT 0,
    offense_sacks_allowed INTEGER NOT NULL DEFAULT 0,
    defense_sacks INTEGER NOT NULL DEFAULT 0,
    offense_fumbles_lost INTEGER NOT NULL DEFAULT 0,
    defense_fumbles_recovered INTEGER NOT NULL DEFAULT 0,
    defense_fumble_touchdowns INTEGER NOT NULL DEFAULT 0,
    defense_interception_touchdowns INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(team_id, year)
);

DROP TABLE IF EXISTS nfl_game_player_stats_2024;

-- Add winning_team column to nfl_schedule table
ALTER TABLE nfl_schedule ADD COLUMN winning_team UUID REFERENCES nfl_teams(id);

